server:
  port: 7979
  tomcat:
    uri-encoding: UTF-8
spring:
  profiles:
    active: @profileActive@
  application:
    name: @pom.artifactId@
  cloud:
    config:
      uri: http://admin:admin@mall-discovery:8080/
      label: master
  http:
    encoding:
      enabled: true
      charset: UTF-8
      force: true
    multipart:
      enabled: true
      max-request-size: 50MB
      max-file-size: 50MB
  boot:
    admin:
      username: admin
      password: admin
management:
  security:
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@mall-eureka:8761/eureka/
    instance:
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  force-original-query-string-encoding: true
  routes:
    uac-route:
      path: /uac/**
      sensitiveHeaders:
      service-id: mall-provider-uac
      ribbon:
        eager-load:
          enabled: true
        max-auto-retries: 1
        max-auto-retries-next-server: 2
        ok-to-retry-on-all-operations: false
        connect-timeout: 10000
        read-timeout: 10000
    opc-route:
      path: /opc/**
      sensitiveHeaders:
      service-id: mall-provider-opc
      ribbon:
        eager-load:
          enabled: true
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: false
        ConnectTimeout: 10000
        ReadTimeout: 10000
ribbon:
  eager-load:
    enabled: true
  max-auto-retries: 1
  max-auto-retries-next-server: 2
  ok-to-retry-on-all-operations: false
  connect-timeout: 60000
  read-timeout: 60000
security:
  oauth2:
    client:
      clientId: mall-client-gateway
      clientSecret: mallClientSecret
      access-token-uri: http://mall-gateway:7979/uac/oauth/token
      user-authorization-uri: http://mall-gateway:7979/uac/oauth/authorize
    resource:
      user-info-uri: http://mall-provider-uac:8081/user
      prefer-token-info: false
      jwt:
        key-uri: http://mall-provider-uac:8081/oauth/token_key
logging:
  level.root: info
  path: logs/
  file: ${spring.application.name}.log
mall:
  enableSqlLogInterceptor: false

