server:
  port: 8761
spring:
  profiles:
    active: @profileActive@
  application:
    name: @pom.artifactId@
security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin
eureka:
  server:
    enable-self-preservation: false #关闭自我保护模式
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #是否向服务注册中心注册自己
    fetch-registry: false #是否检索服务
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
logging:
  level.root: info
  path: logs/
  file: ${spring.application.name}.log
