server:
  port: 8080
spring:
  profiles:
    active: @profileActive@
  application:
    name: @pom.artifactId@
  boot:
    admin:
      username: ${security.user.name:admin}
      password: ${security.user.password:admin}
  cloud:
    config:
      server:
        git:
          uri: https://github.com/git8023love/mall-cloud.git
          username:
          password:
          search-paths: /* # '{application}'
security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@mall-eureka:8761/eureka/
    instance:
      instance-id: ${spring.application.name}:${spring.cloud.client.ipAddress}:${server.port}
encrypt:
  key-store:
    location: classpath:/server.jks
    password: jeff-storepass
    alias: jeff-key-store
    secret: jeff-keypass
logging:
  level.root: info
  path: logs/
  file: ${spring.application.name}.log